# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Alexandre/Desktop/project_4/project_4.cache/wt [current_project]
set_property parent.project_path C:/Users/Alexandre/Desktop/project_4/project_4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Alexandre/Desktop/project_4/project_4.srcs/sources_1/imports/Desktop/Multiplicador.vhd
  C:/Users/Alexandre/Desktop/project_4/project_4.srcs/sources_1/imports/Desktop/Somador.vhd
  C:/Users/Alexandre/Desktop/project_4/project_4.srcs/sources_1/imports/Desktop/Shifter.vhd
  C:/Users/Alexandre/Desktop/project_4/project_4.srcs/sources_1/imports/Desktop/PicoBlaze_Files/VHDL/kcpsm6.vhd
  C:/Users/Alexandre/Desktop/project_4/project_4.srcs/sources_1/imports/Desktop/Decodificador.vhd
  C:/Users/Alexandre/Desktop/project_4/project_4.srcs/sources_1/new/top_3.vhd
  C:/Users/Alexandre/Desktop/project_4/project_4.srcs/sources_1/new/top.vhd
  C:/Users/Alexandre/Desktop/project_4/project_4.srcs/sources_1/new/top_2.vhd
  C:/Users/Alexandre/Desktop/project_4/project_4.srcs/sources_1/new/global_top.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Alexandre/Desktop/project_4/project_4.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Alexandre/Desktop/project_4/project_4.srcs/constrs_1/imports/Desktop/Basys3_Master.xdc]


synth_design -top global_top -part xc7a35tcpg236-1


write_checkpoint -force -noxdef global_top.dcp

catch { report_utilization -file global_top_utilization_synth.rpt -pb global_top_utilization_synth.pb }
